"""
StackBlitz Preview Utility
Generates and opens a StackBlitz preview for a generated Angular component.

Used by:
- main.py (--preview flag)
- Can be run standalone: python stackblitz_preview.py component.ts
"""

import os
import sys
import tempfile
import webbrowser


def generate_stackblitz_html(component_code: str) -> str:
    """
    Generate HTML that opens StackBlitz with the given Angular component.

    Uses StackBlitz's POST API with individual named form fields.

    Args:
        component_code: Angular TypeScript component code

    Returns:
        HTML string with auto-submitting form
    """
    files = {
        "src/app/app.component.ts": component_code,
        "src/app/app.module.ts": (
            "import { NgModule } from '@angular/core';\n"
            "import { BrowserModule } from '@angular/platform-browser';\n"
            "import { AppComponent } from './app.component';\n\n"
            "@NgModule({\n"
            "  declarations: [AppComponent],\n"
            "  imports: [BrowserModule],\n"
            "  bootstrap: [AppComponent]\n"
            "})\n"
            "export class AppModule {}\n"
        ),
        "src/styles.css": (
            "@import url('https://fonts.googleapis.com/css2?family=Inter:"
            "wght@400;500;600;700&display=swap');\n\n"
            "* {\n"
            "  font-family: 'Inter', sans-serif;\n"
            "  box-sizing: border-box;\n"
            "  margin: 0;\n"
            "  padding: 0;\n"
            "}\n\n"
            "body {\n"
            "  background-color: #0f172a;\n"
            "  color: #f1f5f9;\n"
            "  padding: 2rem;\n"
            "}\n"
        ),
    }

    file_inputs = ""
    for path, content in files.items():
        safe_content = (
            content
            .replace("&", "&amp;")
            .replace('"', "&quot;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
        )
        file_inputs += (
            f'<input type="hidden" name="project[files][{path}]" '
            f'value="{safe_content}">\n'
        )

    html = f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>Opening StackBlitz...</title></head>
<body style="font-family:sans-serif;padding:2rem;background:#0f172a;color:#f1f5f9;">
    <h2>🚀 Opening StackBlitz...</h2>
    <p style="color:#94a3b8;margin-top:0.5rem;">
        Your component is loading. If nothing opens, check your pop-up blocker.
    </p>
    <form id="sb" method="POST" action="https://stackblitz.com/run" target="_blank">
        <input type="hidden" name="project[title]" value="Generated Angular Component">
        <input type="hidden" name="project[description]"
               value="Auto-generated by Governed Angular UI Generator">
        <input type="hidden" name="project[template]" value="angular-cli">
        {file_inputs}
    </form>
    <script>
        document.getElementById('sb').submit();
        setTimeout(function() {{
            document.querySelector('h2').textContent = '✅ StackBlitz Opened!';
            document.querySelector('p').textContent =
                'You can close this tab now.';
        }}, 1200);
    </script>
</body>
</html>"""

    return html


def open_stackblitz_preview(component_code: str) -> str:
    """
    Write HTML to a temp file and open it in the default browser.

    Args:
        component_code: Angular TypeScript component code

    Returns:
        Path to the temporary HTML file
    """
    html = generate_stackblitz_html(component_code)

    # Write to temp file (not deleted immediately so browser can load it)
    tmp = tempfile.NamedTemporaryFile(
        mode='w',
        suffix='.html',
        prefix='stackblitz_preview_',
        delete=False,
        encoding='utf-8'
    )
    tmp.write(html)
    tmp.close()

    # Open in default browser
    webbrowser.open(f"file://{tmp.name}")

    return tmp.name


if __name__ == "__main__":
    """Standalone usage: python stackblitz_preview.py component.ts"""
    if len(sys.argv) < 2:
        print("Usage: python stackblitz_preview.py <component_file.ts>")
        print("Example: python stackblitz_preview.py generated.component.ts")
        sys.exit(1)

    component_file = sys.argv[1]

    if not os.path.exists(component_file):
        print(f"❌ File not found: {component_file}")
        sys.exit(1)

    with open(component_file, 'r', encoding='utf-8') as f:
        code = f.read()

    print(f"🚀 Opening StackBlitz preview for: {component_file}")
    html_file = open_stackblitz_preview(code)
    print(f"✅ Browser opened")
    print(f"📄 Temp file: {html_file}")