"""
Streamlit Inspection Layer for Governed Angular UI Generator

IMPORTANT: This is NOT the product. This is a read-only visual debugger.
The core system (agent_loop.py, generator.py, validator.py) is backend-first.
This UI exists ONLY to visualize agent execution for evaluation purposes.

The system works fully via CLI without this interface.
"""

import streamlit as st
import sys
import os
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from agent_loop import AgentLoop


def build_stackblitz_launcher(component_code: str) -> str:
    """
    Build a self-contained HTML launcher that opens StackBlitz when opened in a browser.

    WHY THIS APPROACH:
    Streamlit's components.html() renders inside a sandboxed iframe that is missing
    the 'allow-popups-to-escape-sandbox' attribute. This means:
    - window.open() opens a blank tab that can't receive form submissions
    - form.submit() with target="_blank" is blocked as a popup
    - External SDK scripts are blocked by Streamlit Cloud's CSP
    All JavaScript-based approaches fail inside Streamlit's iframe.

    THE SOLUTION:
    Generate a standalone HTML file the user downloads and opens directly in their
    browser. Outside any iframe, a plain form.submit() navigates to StackBlitz with
    no restrictions whatsoever. This is 100% reliable on every browser.

    The HTML auto-submits on load — user just opens the file and StackBlitz appears.

    Args:
        component_code: Generated Angular TypeScript component code

    Returns:
        HTML string for the launcher file
    """
    files = {
        "src/app/app.component.ts": component_code,
        "src/app/app.module.ts": (
            "import { NgModule } from '@angular/core';\n"
            "import { BrowserModule } from '@angular/platform-browser';\n"
            "import { AppComponent } from './app.component';\n\n"
            "@NgModule({\n"
            "  declarations: [AppComponent],\n"
            "  imports: [BrowserModule],\n"
            "  bootstrap: [AppComponent]\n"
            "})\n"
            "export class AppModule {}\n"
        ),
        "src/styles.css": (
            "@import url('https://fonts.googleapis.com/css2?family=Inter:"
            "wght@400;500;600;700&display=swap');\n\n"
            "* { font-family: 'Inter', sans-serif; box-sizing: border-box; "
            "margin: 0; padding: 0; }\n\n"
            "body { background-color: #0f172a; color: #f1f5f9; padding: 2rem; }\n"
        ),
    }

    inputs = ""
    for path, content in files.items():
        safe = (
            content
            .replace("&", "&amp;")
            .replace('"', "&quot;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
        )
        inputs += (
            f'    <input type="hidden" name="project[files][{path}]" '
            f'value="{safe}">\n'
        )

    return f"""<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Opening StackBlitz...</title>
  <style>
    * {{ box-sizing: border-box; margin: 0; padding: 0; }}
    body {{
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
      background: #0f172a; color: #f1f5f9;
      display: flex; justify-content: center; align-items: center;
      min-height: 100vh;
    }}
    .card {{
      text-align: center; padding: 2.5rem 2rem;
      background: rgba(255,255,255,0.05);
      border: 1px solid rgba(255,255,255,0.1);
      border-radius: 12px; max-width: 420px; width: 90%;
    }}
    .spinner {{
      width: 44px; height: 44px;
      border: 3px solid rgba(99,102,241,0.25);
      border-top-color: #6366f1;
      border-radius: 50%;
      animation: spin 0.8s linear infinite;
      margin: 0 auto 1.5rem;
    }}
    @keyframes spin {{ to {{ transform: rotate(360deg); }} }}
    h2 {{ font-size: 1.25rem; margin-bottom: 0.5rem; color: #f1f5f9; }}
    p {{ color: #94a3b8; font-size: 0.875rem; line-height: 1.5; }}
  </style>
</head>
<body>
  <div class="card">
    <div class="spinner"></div>
    <h2>Opening StackBlitz...</h2>
    <p>Your Angular component is loading.<br>You can close this tab afterward.</p>
  </div>

  <form id="sb" method="POST" action="https://stackblitz.com/run">
    <input type="hidden" name="project[title]" value="Generated Angular Component">
    <input type="hidden" name="project[description]"
           value="Auto-generated by Governed Angular UI Generator">
    <input type="hidden" name="project[template]" value="angular-cli">
{inputs}
  </form>

  <script>
    // No target="_blank" — this file opens in its own browser tab.
    // Direct submit navigates this tab straight to StackBlitz.
    // No popup blockers, no iframe sandbox, no CSP issues.
    window.addEventListener('load', function() {{
      document.getElementById('sb').submit();
    }});
  </script>
</body>
</html>"""


def main():
    """Streamlit app for visualizing agent execution."""

    st.title("Agent Execution Inspector")
    st.caption("Read-only debugger for agentic code generation system")

    st.warning(
        "⚠️ This is an OPTIONAL inspection tool. "
        "The core system is backend-first and CLI-based. "
        "This UI is for visualization only."
    )

    # Session state init
    # Required because Streamlit reruns the entire script on every widget interaction.
    # Without session_state, clicking any button after generation loses the result.
    if "result" not in st.session_state:
        st.session_state.result = None
    if "last_prompt" not in st.session_state:
        st.session_state.last_prompt = None

    # Sidebar
    with st.sidebar:
        st.header("Configuration")

        api_key = st.text_input(
            "Google API Key",
            type="password",
            help="Required for code generation with Gemini"
        )

        model_name = st.text_input(
            "Model Name",
            value="gemini-2.5-flash-lite",
            help="Gemini model to use"
        )

        max_retries = st.number_input(
            "Max Retries",
            min_value=1,
            max_value=5,
            value=2,
            help="Maximum total iterations (1 generation + N-1 corrections)"
        )

        verbose = st.checkbox(
            "Verbose Mode",
            value=False,
            help="Print execution logs to console"
        )

        st.divider()
        st.caption("Backend-First Architecture")
        st.caption("Agent loop is the primary artifact")
        st.caption("UI is non-essential inspection tool")

    # Input
    st.header("1. Input Prompt")
    user_prompt = st.text_area(
        "Natural Language UI Description",
        placeholder="Example: A dashboard page with a card showing product name and price",
        height=100
    )

    if st.button("Execute Agent Loop", type="primary", disabled=not user_prompt):
        if not api_key:
            st.error("Please provide a Google API key in the sidebar")
        else:
            if model_name:
                os.environ["MODEL_NAME"] = model_name

            with st.spinner("Initializing agent loop..."):
                try:
                    loop = AgentLoop(
                        design_system_path="design-system.json",
                        api_key=api_key,
                        max_retries=max_retries
                    )
                except Exception as e:
                    st.error(f"Failed to initialize agent loop: {e}")
                    st.stop()

            with st.spinner("Executing agent loop..."):
                try:
                    result = loop.run(user_prompt, verbose=verbose)
                except Exception as e:
                    st.error(f"Agent loop execution failed: {e}")
                    st.stop()

            st.session_state.result = result
            st.session_state.last_prompt = user_prompt

    # Display results (persists across reruns via session_state)
    if st.session_state.result is not None:
        display_execution_results(
            st.session_state.result,
            st.session_state.last_prompt,
            max_retries
        )


def display_execution_results(result: dict, prompt: str, max_retries: int):
    """
    Display execution results. Called on every rerun while session_state.result exists.
    Read-only — no generation logic here.
    """

    st.header("2. Execution Summary")

    col1, col2, col3 = st.columns(3)
    with col1:
        st.metric("Status", "✅ SUCCESS" if result["success"] else "❌ FAILED")
    with col2:
        st.metric("Iterations Used", result["iterations"])
    with col3:
        st.metric("Max Allowed", max_retries)

    st.subheader("User Prompt")
    st.code(prompt, language=None)

    # Execution trace
    st.header("3. Agent Execution Trace")
    history = result.get("history", [])

    if not history:
        st.warning("No execution history available")
        return

    for attempt in history:
        iteration_num = attempt["iteration"]
        validation_report = attempt["validation_report"]
        is_valid = validation_report["valid"]
        errors = validation_report.get("errors", [])

        status_icon = "✅" if is_valid else "❌"
        with st.expander(
            f"{status_icon} Iteration {iteration_num} — "
            f"{'VALID' if is_valid else f'INVALID ({len(errors)} error(s))'}",
            expanded=(iteration_num == 1 or not is_valid)
        ):
            if is_valid:
                st.success("Validation PASSED")
            else:
                st.error(f"Validation FAILED — {len(errors)} error(s)")
                st.subheader("Validation Errors")
                for i, error in enumerate(errors, 1):
                    st.markdown(f"{i}. `{error}`")

            st.subheader("Generated Code")
            code = attempt.get("code", "")
            if code:
                st.code(code, language="typescript", line_numbers=True)
            else:
                st.warning("No code generated")

            with st.expander("Raw Validation Report"):
                st.json(validation_report)

    # Final result
    st.header("4. Final Result")

    if result["success"]:
        st.success(
            f"✅ Code generation successful after {result['iterations']} iteration(s)"
        )

        final_code = result.get("code", "")
        if final_code:
            st.subheader("Final Generated Code")
            with st.expander("📄 View Full Code", expanded=True):
                st.code(final_code, language="typescript", line_numbers=True)

            st.caption(f"Code length: {len(final_code)} characters")

            st.divider()
            st.subheader("Export Options")

            col1, col2 = st.columns(2)

            with col1:
                # Download the .ts component file
                st.download_button(
                    label="📥 Download Component (.ts)",
                    data=final_code,
                    file_name="generated.component.ts",
                    mime="text/plain",
                    use_container_width=True
                )

            with col2:
                # Download the StackBlitz launcher HTML
                # User opens this file -> StackBlitz opens automatically
                launcher_html = build_stackblitz_launcher(final_code)
                st.download_button(
                    label="🚀 Download StackBlitz Launcher",
                    data=launcher_html,
                    file_name="open-in-stackblitz.html",
                    mime="text/html",
                    use_container_width=True
                )

            # Clear instructions so user knows what to do
            st.info(
                "**To preview in StackBlitz:** Click '🚀 Download StackBlitz Launcher', "
                "then open the downloaded `open-in-stackblitz.html` file in your browser. "
                "StackBlitz will open automatically with your component loaded."
            )

    else:
        st.error(
            f"❌ Code generation failed after {result['iterations']} iteration(s)"
        )
        st.error(f"Error: {result.get('error', 'Unknown error')}")

        if result.get("code"):
            st.subheader("Last Generated Code (Invalid)")
            st.code(result["code"], language="typescript", line_numbers=True)

    with st.expander("Raw Execution Object (Debug)"):
        st.json(result)


if __name__ == "__main__":
    if not os.path.exists("design-system.json"):
        st.error(
            "❌ design-system.json not found. "
            "Run from the project root:\n\n"
            "```\nstreamlit run demo/streamlit_app.py\n```"
        )
        st.stop()

    main()